export interface Product {
  id: number
  name: string
  price: number
  priceText: string
  originalPrice?: string
  rating: number
  image: string
  category: string
  description: string
  brand: string
  inStock: boolean
  features: string[]
  soldCount: string
  isOnSale?: boolean
  specifications?: Record<string, string>
}

export const products: Product[] = [
  // Pesticides & Insecticides (40+ products)
  {
    id: 1,
    name: "Adengo Xtra 465ml",
    price: 2185,
    priceText: "Rs. 2,185",
    originalPrice: "Rs. 2,615",
    rating: 4.5,
    image: "/images/products/adengo-xtra.jpg",
    category: "pesticides",
    description: "Advanced herbicide for effective weed control in corn and other crops.",
    brand: "Bayer",
    inStock: true,
    features: ["Pre & post emergence", "Broad spectrum", "Long lasting"],
    soldCount: "145 Sold",
  },
  {
    id: 2,
    name: "Regent 80wg Insecticide",
    price: 1199,
    priceText: "Rs. 1,199",
    originalPrice: "Rs. 1,629",
    rating: 4.8,
    image: "/images/products/regent-80wg.jpg",
    category: "pesticides",
    description: "Systemic insecticide for control of termites, aphids and other pests.",
    brand: "BASF",
    inStock: true,
    features: ["Systemic action", "Soil & foliar pests", "Termite control"],
    soldCount: "2149 Sold",
    isOnSale: true,
  },
  {
    id: 3,
    name: "Cardinal 80wg Insecticide",
    price: 635,
    priceText: "Rs. 635",
    originalPrice: "Rs. 1,065",
    rating: 4.3,
    image: "/images/products/cardinal-80wg.jpg",
    category: "pesticides",
    description: "Effective insecticide for control of sucking and chewing pests.",
    brand: "Cardinal",
    inStock: true,
    features: ["Sucking pests", "Chewing pests", "Multi-crop"],
    soldCount: "446 Sold",
  },
  {
    id: 4,
    name: "Xuanlijing 45wg",
    price: 675,
    priceText: "Rs. 675",
    originalPrice: "Rs. 1,105",
    rating: 4.2,
    image: "/images/products/xuanlijing-45wg.jpg",
    category: "pesticides",
    description: "Premium fungicide for disease control in various crops.",
    brand: "Xuanlijing",
    inStock: true,
    features: ["Disease control", "Broad spectrum", "Preventive action"],
    soldCount: "75 Sold",
  },
  {
    id: 5,
    name: "Agenda 25EC",
    price: 14250,
    priceText: "Rs. 14,250",
    originalPrice: "Rs. 14,680",
    rating: 4.6,
    image: "/images/products/agenda-25ec.jpg",
    category: "pesticides",
    description: "Professional grade herbicide for selective weed control.",
    brand: "Agenda",
    inStock: true,
    features: ["Selective herbicide", "Professional grade", "Long lasting"],
    soldCount: "38 Sold",
  },
  {
    id: 6,
    name: "Confest 25wg",
    price: 465,
    priceText: "Rs. 465",
    originalPrice: "Rs. 895",
    rating: 4.1,
    image: "/images/products/confest-25wg.jpg",
    category: "pesticides",
    description: "Effective pest control solution for multiple crop types.",
    brand: "Confest",
    inStock: true,
    features: ["Multi-crop", "Pest control", "Cost effective"],
    soldCount: "115 Sold",
  },
  {
    id: 7,
    name: "Phytofix 100ml",
    price: 385,
    priceText: "Rs. 385",
    originalPrice: "Rs. 815",
    rating: 4.7,
    image: "/images/products/phytofix-100ml.jpg",
    category: "pesticides",
    description: "Plant growth regulator and disease prevention solution.",
    brand: "Phytofix",
    inStock: true,
    features: ["Growth regulator", "Disease prevention", "Plant health"],
    soldCount: "3007 Sold",
  },
  {
    id: 8,
    name: "Martha 1kg Fungicide",
    price: 1295,
    priceText: "Rs. 1,295",
    originalPrice: "Rs. 1,725",
    rating: 4.5,
    image: "/images/products/martha-fungicide.jpg",
    category: "pesticides",
    description: "Broad spectrum fungicide for various fungal diseases.",
    brand: "Martha",
    inStock: true,
    features: ["Broad spectrum", "Fungal control", "Preventive action"],
    soldCount: "203 Sold",
  },
  {
    id: 9,
    name: "Humber 500ML",
    price: 850,
    priceText: "Rs. 850",
    originalPrice: "Rs. 1,280",
    rating: 4.2,
    image: "/images/products/humber-500ml.jpg",
    category: "pesticides",
    description: "Effective pest control solution in convenient packaging.",
    brand: "Humber",
    inStock: true,
    features: ["Pest control", "Convenient size", "Effective formula"],
    soldCount: "0 Sold",
  },
  {
    id: 10,
    name: "Gabbar 500ML",
    price: 1150,
    priceText: "Rs. 1,150",
    originalPrice: "Rs. 1,580",
    rating: 4.3,
    image: "/images/products/gabbar-500ml.jpg",
    category: "pesticides",
    description: "Powerful insecticide for comprehensive pest management.",
    brand: "Gabbar",
    inStock: true,
    features: ["Powerful formula", "Pest management", "Long lasting"],
    soldCount: "0 Sold",
  },
  {
    id: 11,
    name: "Sulphur 80WDG",
    price: 960,
    priceText: "Rs. 960",
    originalPrice: "Rs. 1,390",
    rating: 4.1,
    image: "/images/products/sulphur-80wdg.jpg",
    category: "pesticides",
    description: "Fungicide and miticide for disease and mite control.",
    brand: "Sulphur",
    inStock: true,
    features: ["Fungicide", "Miticide", "Disease control"],
    soldCount: "2 Sold",
  },
  {
    id: 12,
    name: "Clank Extra",
    price: 685,
    priceText: "Rs. 685",
    originalPrice: "Rs. 1,115",
    rating: 4.0,
    image: "/images/products/clank-extra.jpg",
    category: "pesticides",
    description: "Enhanced pest control with improved formulation.",
    brand: "Clank",
    inStock: true,
    features: ["Enhanced formula", "Pest control", "Improved action"],
    soldCount: "19 Sold",
  },
  {
    id: 13,
    name: "Clodinafop 15wp",
    price: 975,
    priceText: "Rs. 975",
    originalPrice: "Rs. 1,405",
    rating: 4.2,
    image: "/images/products/clodinafop-15wp.jpg",
    category: "pesticides",
    description: "Selective herbicide for grass weed control in wheat.",
    brand: "Clodinafop",
    inStock: true,
    features: ["Selective herbicide", "Grass weed control", "Wheat specialist"],
    soldCount: "101 Sold",
  },
  {
    id: 14,
    name: "Starane M 50EC",
    price: 1725,
    priceText: "Rs. 1,725",
    originalPrice: "Rs. 2,155",
    rating: 4.4,
    image: "/images/products/starane-m-50ec.jpg",
    category: "pesticides",
    description: "Broad-leaf herbicide for cereal crops.",
    brand: "Starane",
    inStock: true,
    features: ["Broad-leaf herbicide", "Cereal crops", "Selective action"],
    soldCount: "0 Sold",
  },
  {
    id: 15,
    name: "Fungi Fix",
    price: 1150,
    priceText: "Rs. 1,150",
    originalPrice: "Rs. 1,580",
    rating: 4.3,
    image: "/images/products/fungi-fix.jpg",
    category: "pesticides",
    description: "Comprehensive fungicide for disease management.",
    brand: "Fungi Fix",
    inStock: true,
    features: ["Comprehensive fungicide", "Disease management", "Broad spectrum"],
    soldCount: "0 Sold",
  },
  {
    id: 16,
    name: "Atrazine 50WP",
    price: 485,
    priceText: "Rs. 485",
    originalPrice: "Rs. 915",
    rating: 4.1,
    image: "/images/products/atrazine-50wp.jpg",
    category: "pesticides",
    description: "Pre and post-emergence herbicide for maize and sugarcane.",
    brand: "Atrazine",
    inStock: true,
    features: ["Pre-emergence", "Post-emergence", "Maize specialist"],
    soldCount: "287 Sold",
  },
  {
    id: 17,
    name: "Cypermethrin 25EC",
    price: 795,
    priceText: "Rs. 795",
    originalPrice: "Rs. 1,225",
    rating: 4.4,
    image: "/images/products/cypermethrin-25ec.jpg",
    category: "pesticides",
    description: "Broad spectrum insecticide for multiple pest control.",
    brand: "Cypermethrin",
    inStock: true,
    features: ["Broad spectrum", "Multiple pests", "Quick action"],
    soldCount: "156 Sold",
  },
  {
    id: 18,
    name: "Imidacloprid 17.8SL",
    price: 1285,
    priceText: "Rs. 1,285",
    originalPrice: "Rs. 1,715",
    rating: 4.6,
    image: "/images/products/imidacloprid-17-8sl.jpg",
    category: "pesticides",
    description: "Systemic insecticide for sucking pest control.",
    brand: "Imidacloprid",
    inStock: true,
    features: ["Systemic action", "Sucking pests", "Long residual"],
    soldCount: "89 Sold",
  },
  {
    id: 19,
    name: "Chlorpyrifos 40EC",
    price: 925,
    priceText: "Rs. 925",
    originalPrice: "Rs. 1,355",
    rating: 4.3,
    image: "/images/products/chlorpyrifos-40ec.jpg",
    category: "pesticides",
    description: "Organophosphate insecticide for soil and foliar pests.",
    brand: "Chlorpyrifos",
    inStock: true,
    features: ["Organophosphate", "Soil pests", "Foliar application"],
    soldCount: "234 Sold",
  },
  {
    id: 20,
    name: "Mancozeb 75WP",
    price: 685,
    priceText: "Rs. 685",
    originalPrice: "Rs. 1,115",
    rating: 4.2,
    image: "/images/products/mancozeb-75wp.jpg",
    category: "pesticides",
    description: "Protective fungicide for disease prevention.",
    brand: "Mancozeb",
    inStock: true,
    features: ["Protective fungicide", "Disease prevention", "Multi-crop"],
    soldCount: "178 Sold",
  },

  // Fertilizers & Nutrients (35+ products)
  {
    id: 21,
    name: "Green Gold Fertilizer",
    price: 1800,
    priceText: "Rs. 1,800",
    originalPrice: "Rs. 2,230",
    rating: 4.6,
    image: "/images/products/green-gold-fertilizer.jpg",
    category: "fertilizers",
    description: "Premium organic fertilizer for enhanced soil fertility.",
    brand: "Green Gold",
    inStock: true,
    features: ["100% organic", "Soil fertility", "Slow release"],
    soldCount: "63 Sold",
  },
  {
    id: 22,
    name: "Silikalzium 1kg",
    price: 1645,
    priceText: "Rs. 1,645",
    originalPrice: "Rs. 2,075",
    rating: 4.4,
    image: "/images/products/silikalzium.jpg",
    category: "fertilizers",
    description: "Silicon and calcium supplement for stronger plant structure.",
    brand: "Silikalzium",
    inStock: true,
    features: ["Silicon supplement", "Disease resistance", "Plant strength"],
    soldCount: "92 Sold",
  },
  {
    id: 23,
    name: "Silikalzium 2kg",
    price: 3210,
    priceText: "Rs. 3,210",
    originalPrice: "Rs. 3,640",
    rating: 4.4,
    image: "/images/products/silikalzium-2kg.jpg",
    category: "fertilizers",
    description: "Silicon and calcium supplement in larger pack size.",
    brand: "Silikalzium",
    inStock: true,
    features: ["Silicon supplement", "Disease resistance", "Economy pack"],
    soldCount: "104 Sold",
  },
  {
    id: 24,
    name: "Vita Humate 1Kg",
    price: 595,
    priceText: "Rs. 595",
    originalPrice: "Rs. 1,025",
    rating: 4.3,
    image: "/images/products/vita-humate.jpg",
    category: "fertilizers",
    description: "Organic humic acid supplement for improved nutrient uptake.",
    brand: "Vita",
    inStock: true,
    features: ["Humic acid", "Nutrient uptake", "Soil conditioner"],
    soldCount: "14 Sold",
  },
  {
    id: 25,
    name: "Natural Gypsum",
    price: 895,
    priceText: "Rs. 895",
    originalPrice: "Rs. 1,325",
    rating: 4.2,
    image: "/images/products/natural-gypsum.jpg",
    category: "fertilizers",
    description: "Natural gypsum for soil structure improvement.",
    brand: "Natural",
    inStock: true,
    features: ["Soil structure", "Calcium sulfur", "pH balance"],
    soldCount: "220 Sold",
  },
  {
    id: 26,
    name: "Rhizophos Bio Fertilizer",
    price: 1595,
    priceText: "Rs. 1,595",
    originalPrice: "Rs. 2,025",
    rating: 4.7,
    image: "/images/products/rhizophos-bio.jpg",
    category: "fertilizers",
    description: "Phosphorus solubilizing bacteria for enhanced phosphorus availability.",
    brand: "Rhizophos",
    inStock: true,
    features: ["Bio fertilizer", "Phosphorus solubilizing", "Root development"],
    soldCount: "2037 Sold",
  },
  {
    id: 27,
    name: "LCI Amino Acids",
    price: 3450,
    priceText: "Rs. 3,450",
    originalPrice: "Rs. 3,880",
    rating: 4.4,
    image: "/images/products/lci-amino-acids.jpg",
    category: "fertilizers",
    description: "Essential amino acids for plant growth and development.",
    brand: "LCI",
    inStock: true,
    features: ["Amino acids", "Plant growth", "Development"],
    soldCount: "0 Sold",
  },
  {
    id: 28,
    name: "Neu farm Neu Power",
    price: 3450,
    priceText: "Rs. 3,450",
    originalPrice: "Rs. 3,880",
    rating: 4.5,
    image: "/images/products/neu-farm-neu-power.jpg",
    category: "fertilizers",
    description: "Advanced nutrient formula for enhanced crop performance.",
    brand: "Neu Farm",
    inStock: true,
    features: ["Advanced nutrients", "Crop performance", "Enhanced formula"],
    soldCount: "0 Sold",
  },
  {
    id: 29,
    name: "Ammonium Sulphate",
    price: 3980,
    priceText: "Rs. 3,980",
    originalPrice: "Rs. 4,410",
    rating: 4.3,
    image: "/images/products/ammonium-sulphate.jpg",
    category: "fertilizers",
    description: "Nitrogen and sulfur fertilizer for improved plant nutrition.",
    brand: "Ammonium",
    inStock: true,
    features: ["Nitrogen source", "Sulfur nutrition", "Plant nutrition"],
    soldCount: "754 Sold",
  },
  {
    id: 30,
    name: "Potash Power",
    price: 14350,
    priceText: "Rs. 14,350",
    originalPrice: "Rs. 14,780",
    rating: 4.6,
    image: "/images/products/potash-power.jpg",
    category: "fertilizers",
    description: "High-grade potassium fertilizer for fruit and vegetable crops.",
    brand: "Potash",
    inStock: true,
    features: ["High-grade potassium", "Fruit crops", "Vegetable nutrition"],
    soldCount: "108 Sold",
  },
  {
    id: 31,
    name: "Zingreen 27 3kg",
    price: 2250,
    priceText: "Rs. 2,250",
    originalPrice: "Rs. 2,680",
    rating: 4.2,
    image: "/images/products/zingreen-27-3kg.jpg",
    category: "fertilizers",
    description: "Zinc fertilizer for micronutrient deficiency correction.",
    brand: "Zingreen",
    inStock: true,
    features: ["Zinc fertilizer", "Micronutrient", "Deficiency correction"],
    soldCount: "39 Sold",
  },
  {
    id: 32,
    name: "Tara Ssp 50kg",
    price: 3150,
    priceText: "Rs. 3,150",
    originalPrice: "Rs. 3,580",
    rating: 4.4,
    image: "/images/products/tara-ssp-50kg.jpg",
    category: "fertilizers",
    description: "Single super phosphate fertilizer for phosphorus nutrition.",
    brand: "Tara",
    inStock: true,
    features: ["Phosphorus fertilizer", "Single super phosphate", "Bulk pack"],
    soldCount: "600 Sold",
  },
  {
    id: 33,
    name: "Ferro Max",
    price: 2050,
    priceText: "Rs. 2,050",
    originalPrice: "Rs. 2,480",
    rating: 4.1,
    image: "/images/products/ferro-max.jpg",
    category: "fertilizers",
    description: "Iron chelate fertilizer for iron deficiency correction.",
    brand: "Ferro Max",
    inStock: true,
    features: ["Iron chelate", "Deficiency correction", "Micronutrient"],
    soldCount: "0 Sold",
  },
  {
    id: 34,
    name: "Wokozim Power",
    price: 3850,
    priceText: "Rs. 3,850",
    originalPrice: "Rs. 4,280",
    rating: 4.3,
    image: "/images/products/wokozim-power.jpg",
    category: "fertilizers",
    description: "Enzyme-based fertilizer for improved nutrient availability.",
    brand: "Wokozim",
    inStock: true,
    features: ["Enzyme-based", "Nutrient availability", "Soil health"],
    soldCount: "0 Sold",
  },
  {
    id: 35,
    name: "Sulfur Coated Urea",
    price: 4750,
    priceText: "Rs. 4,750",
    originalPrice: "Rs. 5,180",
    rating: 4.5,
    image: "/images/products/sulfur-coated-urea.jpg",
    category: "fertilizers",
    description: "Slow-release nitrogen fertilizer with sulfur coating.",
    brand: "SCU",
    inStock: true,
    features: ["Slow-release nitrogen", "Sulfur coating", "Extended feeding"],
    soldCount: "0 Sold",
  },
  {
    id: 36,
    name: "Potassium K2O",
    price: 5795,
    priceText: "Rs. 5,795",
    originalPrice: "Rs. 6,225",
    rating: 4.4,
    image: "/images/products/potassium-k2o.jpg",
    category: "fertilizers",
    description: "Pure potassium fertilizer for enhanced fruit quality.",
    brand: "K2O",
    inStock: true,
    features: ["Pure potassium", "Fruit quality", "High concentration"],
    soldCount: "0 Sold",
  },
  {
    id: 37,
    name: "Pulwan Bio Fertilizer",
    price: 6950,
    priceText: "Rs. 6,950",
    originalPrice: "Rs. 7,380",
    rating: 4.6,
    image: "/images/products/pulwan-bio.jpg",
    category: "fertilizers",
    description: "Comprehensive bio-fertilizer for sustainable agriculture.",
    brand: "Pulwan",
    inStock: true,
    features: ["Bio-fertilizer", "Sustainable agriculture", "Comprehensive nutrition"],
    soldCount: "0 Sold",
  },
  {
    id: 38,
    name: "NPK 15-15-15",
    price: 2850,
    priceText: "Rs. 2,850",
    originalPrice: "Rs. 3,280",
    rating: 4.3,
    image: "/images/products/npk-15-15-15.jpg",
    category: "fertilizers",
    description: "Balanced NPK fertilizer for all-round plant nutrition.",
    brand: "NPK",
    inStock: true,
    features: ["Balanced nutrition", "All-round feeding", "Complete fertilizer"],
    soldCount: "425 Sold",
  },
  {
    id: 39,
    name: "Calcium Nitrate",
    price: 1950,
    priceText: "Rs. 1,950",
    originalPrice: "Rs. 2,380",
    rating: 4.2,
    image: "/images/products/calcium-nitrate.jpg",
    category: "fertilizers",
    description: "Water-soluble calcium and nitrogen fertilizer.",
    brand: "Calcium",
    inStock: true,
    features: ["Water-soluble", "Calcium nutrition", "Nitrogen source"],
    soldCount: "167 Sold",
  },
  {
    id: 40,
    name: "Magnesium Sulphate",
    price: 1485,
    priceText: "Rs. 1,485",
    originalPrice: "Rs. 1,915",
    rating: 4.1,
    image: "/images/products/magnesium-sulphate.jpg",
    category: "fertilizers",
    description: "Magnesium and sulfur supplement for plant health.",
    brand: "Magnesium",
    inStock: true,
    features: ["Magnesium supplement", "Sulfur nutrition", "Plant health"],
    soldCount: "89 Sold",
  },

  // Seeds & Varieties (30+ products)
  {
    id: 41,
    name: "Bhakkar Star Cotton Seeds",
    price: 7550,
    priceText: "Rs. 7,550",
    originalPrice: "Rs. 7,980",
    rating: 4.6,
    image: "/images/products/bhakkar-star-cotton.jpg",
    category: "seeds",
    description: "High yielding cotton variety with excellent fiber quality.",
    brand: "Bhakkar",
    inStock: true,
    features: ["High yield", "Quality fiber", "Disease resistant"],
    soldCount: "38 Sold",
  },
  {
    id: 42,
    name: "Rhodes Grass Seeds",
    price: 4895,
    priceText: "Rs. 4,895",
    originalPrice: "Rs. 5,325",
    rating: 4.5,
    image: "/images/products/rhodes-grass-seeds.jpg",
    category: "seeds",
    description: "High quality Rhodes grass seeds for fodder production.",
    brand: "Rhodes",
    inStock: true,
    features: ["Fodder grass", "High quality", "Pasture establishment"],
    soldCount: "106 Sold",
  },
  {
    id: 43,
    name: "Basmati 515 Seeds",
    price: 3980,
    priceText: "Rs. 3,980",
    originalPrice: "Rs. 4,410",
    rating: 4.5,
    image: "/images/products/basmati-515-seeds.jpg",
    category: "seeds",
    description: "Premium basmati rice variety with excellent aroma.",
    brand: "Basmati",
    inStock: true,
    features: ["Premium basmati", "Excellent aroma", "Quality grain"],
    soldCount: "166 Sold",
  },
  {
    id: 44,
    name: "Nawan BF 18 Seeds",
    price: 3950,
    priceText: "Rs. 3,950",
    originalPrice: "Rs. 4,380",
    rating: 4.3,
    image: "/images/products/nawan-bf18.jpg",
    category: "seeds",
    description: "High performance hybrid seeds for better yield.",
    brand: "Nawan",
    inStock: true,
    features: ["Hybrid variety", "High yield", "Disease tolerance"],
    soldCount: "0 Sold",
  },
  {
    id: 45,
    name: "Nawan Gatawa Seeds",
    price: 3950,
    priceText: "Rs. 3,950",
    originalPrice: "Rs. 4,380",
    rating: 4.3,
    image: "/images/products/nawan-gatawa.jpg",
    category: "seeds",
    description: "Premium hybrid variety with superior performance.",
    brand: "Nawan",
    inStock: true,
    features: ["Premium hybrid", "Superior performance", "High adaptability"],
    soldCount: "0 Sold",
  },
  {
    id: 46,
    name: "Welcomes Seeds",
    price: 9500,
    priceText: "Rs. 9,500",
    originalPrice: "Rs. 9,930",
    rating: 4.4,
    image: "/images/products/welcomes-seeds.jpg",
    category: "seeds",
    description: "Premium variety seeds with excellent market acceptance.",
    brand: "Welcomes",
    inStock: true,
    features: ["Premium variety", "Market acceptance", "High quality"],
    soldCount: "0 Sold",
  },
  {
    id: 47,
    name: "Red Lady Papaya Seeds",
    price: 21500,
    priceText: "Rs. 21,500",
    originalPrice: "Rs. 21,930",
    rating: 4.8,
    image: "/images/products/red-lady-papaya.jpg",
    category: "seeds",
    description: "Premium papaya variety with excellent fruit quality.",
    brand: "Red Lady",
    inStock: true,
    features: ["Premium variety", "Excellent fruit", "High market value"],
    soldCount: "0 Sold",
  },
  {
    id: 48,
    name: "Kohenoor Seeds",
    price: 5950,
    priceText: "Rs. 5,950",
    originalPrice: "Rs. 6,380",
    rating: 4.5,
    image: "/images/products/kohenoor-seeds.jpg",
    category: "seeds",
    description: "High quality variety with superior characteristics.",
    brand: "Kohenoor",
    inStock: true,
    features: ["High quality", "Superior characteristics", "Proven performance"],
    soldCount: "0 Sold",
  },
  {
    id: 49,
    name: "NARC Super Seeds",
    price: 6450,
    priceText: "Rs. 6,450",
    originalPrice: "Rs. 6,880",
    rating: 4.6,
    image: "/images/products/narc-super.jpg",
    category: "seeds",
    description: "Research-based variety with enhanced traits.",
    brand: "NARC",
    inStock: true,
    features: ["Research-based", "Enhanced traits", "Scientific breeding"],
    soldCount: "30 Sold",
  },
  {
    id: 50,
    name: "FH 333 Cotton Seeds",
    price: 6650,
    priceText: "Rs. 6,650",
    originalPrice: "Rs. 7,080",
    rating: 4.7,
    image: "/images/products/fh-333-cotton.jpg",
    category: "seeds",
    description: "High yielding cotton variety with disease resistance.",
    brand: "FH",
    inStock: true,
    features: ["High yielding", "Disease resistance", "Quality fiber"],
    soldCount: "141 Sold",
  },
  {
    id: 51,
    name: "Tomato Advanta Seeds",
    price: 5855,
    priceText: "Rs. 5,855",
    originalPrice: "Rs. 6,285",
    rating: 4.4,
    image: "/images/products/tomato-advanta.jpg",
    category: "seeds",
    description: "Premium tomato variety for commercial cultivation.",
    brand: "Advanta",
    inStock: true,
    features: ["Premium tomato", "Commercial cultivation", "High yield"],
    soldCount: "13 Sold",
  },
  {
    id: 52,
    name: "Melon Gold 61 Seeds",
    price: 1750,
    priceText: "Rs. 1,750",
    originalPrice: "Rs. 2,180",
    rating: 4.2,
    image: "/images/products/melon-gold-61.jpg",
    category: "seeds",
    description: "Sweet melon variety with excellent taste and quality.",
    brand: "Gold",
    inStock: true,
    features: ["Sweet melon", "Excellent taste", "Quality fruit"],
    soldCount: "12 Sold",
  },
  {
    id: 53,
    name: "Bottle Gourd Seeds",
    price: 2295,
    priceText: "Rs. 2,295",
    originalPrice: "Rs. 2,725",
    rating: 4.1,
    image: "/images/products/bottle-gourd.jpg",
    category: "seeds",
    description: "High quality bottle gourd seeds for vegetable production.",
    brand: "Bottle Gourd",
    inStock: true,
    features: ["High quality", "Vegetable production", "Good yield"],
    soldCount: "139 Sold",
  },
  {
    id: 54,
    name: "Bermuda Grass Seeds",
    price: 1375,
    priceText: "Rs. 1,375",
    originalPrice: "Rs. 1,805",
    rating: 4.0,
    image: "/images/products/bermuda-grass.jpg",
    category: "seeds",
    description: "Durable grass variety for lawns and sports fields.",
    brand: "Bermuda",
    inStock: true,
    features: ["Durable grass", "Lawn variety", "Sports fields"],
    soldCount: "60 Sold",
  },
  {
    id: 55,
    name: "Moong Seed Premium",
    price: 5150,
    priceText: "Rs. 5,150",
    originalPrice: "Rs. 5,580",
    rating: 4.3,
    image: "/images/products/moong-seed.jpg",
    category: "seeds",
    description: "Premium moong bean variety with high protein content.",
    brand: "Moong",
    inStock: true,
    features: ["Premium variety", "High protein", "Good yield"],
    soldCount: "0 Sold",
  },
  {
    id: 56,
    name: "Cluster Beans Seeds",
    price: 895,
    priceText: "Rs. 895",
    originalPrice: "Rs. 1,325",
    rating: 4.0,
    image: "/images/products/cluster-beans.jpg",
    category: "seeds",
    description: "Nutritious cluster beans variety for vegetable farming.",
    brand: "Cluster",
    inStock: true,
    features: ["Nutritious variety", "Vegetable farming", "Good adaptation"],
    soldCount: "0 Sold",
  },
  {
    id: 57,
    name: "Organic Seed Mix",
    price: 1100,
    priceText: "Rs. 1,100",
    originalPrice: "Rs. 1,530",
    rating: 4.2,
    image: "/images/products/organic-seed-mix.jpg",
    category: "seeds",
    description: "Certified organic seed mixture for sustainable farming.",
    brand: "Organic",
    inStock: true,
    features: ["Certified organic", "Seed mixture", "Sustainable farming"],
    soldCount: "0 Sold",
  },
  {
    id: 58,
    name: "Kissan Basmati Premium",
    price: 3850,
    priceText: "Rs. 3,850",
    originalPrice: "Rs. 4,280",
    rating: 4.4,
    image: "/images/products/kissan-basmati.jpg",
    category: "seeds",
    description: "Premium basmati variety for commercial rice production.",
    brand: "Kissan",
    inStock: true,
    features: ["Premium basmati", "Commercial production", "Export quality"],
    soldCount: "0 Sold",
  },
  {
    id: 59,
    name: "Wheat Gold Variety",
    price: 2750,
    priceText: "Rs. 2,750",
    originalPrice: "Rs. 3,180",
    rating: 4.3,
    image: "/images/products/wheat-gold.jpg",
    category: "seeds",
    description: "High yielding wheat variety with disease resistance.",
    brand: "Wheat Gold",
    inStock: true,
    features: ["High yielding", "Disease resistance", "Quality grain"],
    soldCount: "245 Sold",
  },
  {
    id: 60,
    name: "Sunflower Hybrid Seeds",
    price: 1850,
    priceText: "Rs. 1,850",
    originalPrice: "Rs. 2,280",
    rating: 4.2,
    image: "/images/products/sunflower-hybrid.jpg",
    category: "seeds",
    description: "High oil content sunflower hybrid for commercial cultivation.",
    brand: "Sunflower",
    inStock: true,
    features: ["High oil content", "Hybrid variety", "Commercial grade"],
    soldCount: "78 Sold",
  },

  // Specialty Products (15+ products)
  {
    id: 61,
    name: "Nawan Gold Milk Enhancer",
    price: 4950,
    priceText: "Rs. 4,950",
    originalPrice: "Rs. 5,380",
    rating: 4.5,
    image: "/images/products/nawan-gold-milk.jpg",
    category: "specialty",
    description: "Milk production enhancer for dairy animals.",
    brand: "Nawan Gold",
    inStock: true,
    features: ["Milk enhancer", "Dairy animals", "Production booster"],
    soldCount: "0 Sold",
  },
  {
    id: 62,
    name: "Bio Stimulant Plus",
    price: 2850,
    priceText: "Rs. 2,850",
    originalPrice: "Rs. 3,280",
    rating: 4.4,
    image: "/images/products/bio-stimulant-plus.jpg",
    category: "specialty",
    description: "Advanced bio-stimulant for enhanced plant growth.",
    brand: "Bio Plus",
    inStock: true,
    features: ["Bio-stimulant", "Plant growth", "Enhanced performance"],
    soldCount: "45 Sold",
  },
  {
    id: 63,
    name: "Soil Conditioner Pro",
    price: 1950,
    priceText: "Rs. 1,950",
    originalPrice: "Rs. 2,380",
    rating: 4.3,
    image: "/images/products/soil-conditioner-pro.jpg",
    category: "specialty",
    description: "Professional soil conditioning agent for improved structure.",
    brand: "Soil Pro",
    inStock: true,
    features: ["Soil conditioning", "Structure improvement", "Professional grade"],
    soldCount: "67 Sold",
  },
  {
    id: 64,
    name: "Growth Hormone Activator",
    price: 3450,
    priceText: "Rs. 3,450",
    originalPrice: "Rs. 3,880",
    rating: 4.6,
    image: "/images/products/growth-hormone.jpg",
    category: "specialty",
    description: "Natural growth hormone activator for plants.",
    brand: "Growth Pro",
    inStock: true,
    features: ["Growth hormone", "Natural activator", "Plant development"],
    soldCount: "23 Sold",
  },
  {
    id: 65,
    name: "Stress Relief Formula",
    price: 2150,
    priceText: "Rs. 2,150",
    originalPrice: "Rs. 2,580",
    rating: 4.2,
    image: "/images/products/stress-relief.jpg",
    category: "specialty",
    description: "Plant stress relief formula for adverse conditions.",
    brand: "Stress Relief",
    inStock: true,
    features: ["Stress relief", "Adverse conditions", "Plant protection"],
    soldCount: "89 Sold",
  },

  // Additional Products to reach 100+
  {
    id: 66,
    name: "Copper Fungicide 50WP",
    price: 1285,
    priceText: "Rs. 1,285",
    originalPrice: "Rs. 1,715",
    rating: 4.3,
    image: "/images/products/copper-fungicide.jpg",
    category: "pesticides",
    description: "Copper-based fungicide for bacterial and fungal diseases.",
    brand: "Copper",
    inStock: true,
    features: ["Copper-based", "Bacterial diseases", "Fungal control"],
    soldCount: "156 Sold",
  },
  {
    id: 67,
    name: "Deltamethrin 2.8EC",
    price: 895,
    priceText: "Rs. 895",
    originalPrice: "Rs. 1,325",
    rating: 4.4,
    image: "/images/products/deltamethrin.jpg",
    category: "pesticides",
    description: "Pyrethroid insecticide for household and agricultural pests.",
    brand: "Deltamethrin",
    inStock: true,
    features: ["Pyrethroid", "Household pests", "Agricultural use"],
    soldCount: "234 Sold",
  },
  {
    id: 68,
    name: "Glyphosate 41SL",
    price: 1450,
    priceText: "Rs. 1,450",
    originalPrice: "Rs. 1,880",
    rating: 4.5,
    image: "/images/products/glyphosate.jpg",
    category: "pesticides",
    description: "Non-selective herbicide for total vegetation control.",
    brand: "Glyphosate",
    inStock: true,
    features: ["Non-selective", "Total control", "Broad spectrum"],
    soldCount: "189 Sold",
  },
  {
    id: 69,
    name: "Boron 20%",
    price: 1650,
    priceText: "Rs. 1,650",
    originalPrice: "Rs. 2,080",
    rating: 4.2,
    image: "/images/products/boron-20.jpg",
    category: "fertilizers",
    description: "Boron micronutrient for flower and fruit development.",
    brand: "Boron",
    inStock: true,
    features: ["Boron micronutrient", "Flower development", "Fruit quality"],
    soldCount: "78 Sold",
  },
  {
    id: 70,
    name: "Manganese Sulphate",
    price: 1350,
    priceText: "Rs. 1,350",
    originalPrice: "Rs. 1,780",
    rating: 4.1,
    image: "/images/products/manganese-sulphate.jpg",
    category: "fertilizers",
    description: "Manganese micronutrient for enzyme activation.",
    brand: "Manganese",
    inStock: true,
    features: ["Manganese micronutrient", "Enzyme activation", "Plant metabolism"],
    soldCount: "45 Sold",
  },
  {
    id: 71,
    name: "Okra Premium Seeds",
    price: 1250,
    priceText: "Rs. 1,250",
    originalPrice: "Rs. 1,680",
    rating: 4.3,
    image: "/images/products/okra-premium.jpg",
    category: "seeds",
    description: "High yielding okra variety for vegetable production.",
    brand: "Okra",
    inStock: true,
    features: ["High yielding", "Vegetable production", "Premium quality"],
    soldCount: "123 Sold",
  },
  {
    id: 72,
    name: "Chili Hybrid Seeds",
    price: 2850,
    priceText: "Rs. 2,850",
    originalPrice: "Rs. 3,280",
    rating: 4.4,
    image: "/images/products/chili-hybrid.jpg",
    category: "seeds",
    description: "Hot chili hybrid variety with high pungency.",
    brand: "Chili",
    inStock: true,
    features: ["Hot variety", "High pungency", "Hybrid vigor"],
    soldCount: "67 Sold",
  },
  {
    id: 73,
    name: "Cucumber Elite Seeds",
    price: 1950,
    priceText: "Rs. 1,950",
    originalPrice: "Rs. 2,380",
    rating: 4.2,
    image: "/images/products/cucumber-elite.jpg",
    category: "seeds",
    description: "Elite cucumber variety for fresh market production.",
    brand: "Cucumber",
    inStock: true,
    features: ["Elite variety", "Fresh market", "High quality"],
    soldCount: "89 Sold",
  },
  {
    id: 74,
    name: "Carrot Gold Seeds",
    price: 1450,
    priceText: "Rs. 1,450",
    originalPrice: "Rs. 1,880",
    rating: 4.1,
    image: "/images/products/carrot-gold.jpg",
    category: "seeds",
    description: "Golden carrot variety with high beta-carotene content.",
    brand: "Carrot Gold",
    inStock: true,
    features: ["Golden variety", "High beta-carotene", "Nutritious"],
    soldCount: "156 Sold",
  },
  {
    id: 75,
    name: "Spinach Green Seeds",
    price: 850,
    priceText: "Rs. 850",
    originalPrice: "Rs. 1,280",
    rating: 4.0,
    image: "/images/products/spinach-green.jpg",
    category: "seeds",
    description: "Dark green spinach variety rich in iron and vitamins.",
    brand: "Spinach",
    inStock: true,
    features: ["Dark green", "Rich in iron", "Vitamin content"],
    soldCount: "234 Sold",
  },

  // Continue adding more products to reach 100+...
  {
    id: 76,
    name: "Phosphoric Acid 85%",
    price: 2450,
    priceText: "Rs. 2,450",
    originalPrice: "Rs. 2,880",
    rating: 4.3,
    image: "/images/products/phosphoric-acid.jpg",
    category: "fertilizers",
    description: "High concentration phosphoric acid for fertigation.",
    brand: "Phosphoric",
    inStock: true,
    features: ["High concentration", "Fertigation", "Water soluble"],
    soldCount: "67 Sold",
  },
  {
    id: 77,
    name: "Nitric Acid 68%",
    price: 2850,
    priceText: "Rs. 2,850",
    originalPrice: "Rs. 3,280",
    rating: 4.4,
    image: "/images/products/nitric-acid.jpg",
    category: "fertilizers",
    description: "Concentrated nitric acid for hydroponic systems.",
    brand: "Nitric",
    inStock: true,
    features: ["Concentrated", "Hydroponic systems", "pH adjustment"],
    soldCount: "34 Sold",
  },
  {
    id: 78,
    name: "Seaweed Extract",
    price: 1950,
    priceText: "Rs. 1,950",
    originalPrice: "Rs. 2,380",
    rating: 4.5,
    image: "/images/products/seaweed-extract.jpg",
    category: "specialty",
    description: "Natural seaweed extract for plant growth enhancement.",
    brand: "Seaweed",
    inStock: true,
    features: ["Natural extract", "Growth enhancement", "Organic"],
    soldCount: "89 Sold",
  },
  {
    id: 79,
    name: "Mycorrhizal Fungi",
    price: 3450,
    priceText: "Rs. 3,450",
    originalPrice: "Rs. 3,880",
    rating: 4.6,
    image: "/images/products/mycorrhizal-fungi.jpg",
    category: "specialty",
    description: "Beneficial mycorrhizal fungi for root enhancement.",
    brand: "Mycorrhiza",
    inStock: true,
    features: ["Beneficial fungi", "Root enhancement", "Nutrient uptake"],
    soldCount: "23 Sold",
  },
  {
    id: 80,
    name: "Trichoderma Viride",
    price: 1850,
    priceText: "Rs. 1,850",
    originalPrice: "Rs. 2,280",
    rating: 4.4,
    image: "/images/products/trichoderma.jpg",
    category: "specialty",
    description: "Biocontrol agent for soil-borne disease management.",
    brand: "Trichoderma",
    inStock: true,
    features: ["Biocontrol agent", "Disease management", "Soil health"],
    soldCount: "156 Sold",
  },

  // Adding more products to complete 100+
  {
    id: 81,
    name: "Brinjal Hybrid Seeds",
    price: 2250,
    priceText: "Rs. 2,250",
    originalPrice: "Rs. 2,680",
    rating: 4.3,
    image: "/images/products/brinjal-hybrid.jpg",
    category: "seeds",
    description: "High yielding brinjal hybrid for commercial cultivation.",
    brand: "Brinjal",
    inStock: true,
    features: ["High yielding", "Commercial cultivation", "Disease resistant"],
    soldCount: "78 Sold",
  },
  {
    id: 82,
    name: "Cauliflower Premium",
    price: 1650,
    priceText: "Rs. 1,650",
    originalPrice: "Rs. 2,080",
    rating: 4.2,
    image: "/images/products/cauliflower-premium.jpg",
    category: "seeds",
    description: "Premium cauliflower variety with compact heads.",
    brand: "Cauliflower",
    inStock: true,
    features: ["Premium variety", "Compact heads", "Market preferred"],
    soldCount: "134 Sold",
  },
  {
    id: 83,
    name: "Cabbage Elite",
    price: 1450,
    priceText: "Rs. 1,450",
    originalPrice: "Rs. 1,880",
    rating: 4.1,
    image: "/images/products/cabbage-elite.jpg",
    category: "seeds",
    description: "Elite cabbage variety with tight head formation.",
    brand: "Cabbage",
    inStock: true,
    features: ["Elite variety", "Tight heads", "Good storage"],
    soldCount: "167 Sold",
  },
  {
    id: 84,
    name: "Radish Red Seeds",
    price: 750,
    priceText: "Rs. 750",
    originalPrice: "Rs. 1,180",
    rating: 4.0,
    image: "/images/products/radish-red.jpg",
    category: "seeds",
    description: "Red radish variety with crisp texture and mild flavor.",
    brand: "Radish",
    inStock: true,
    features: ["Red variety", "Crisp texture", "Mild flavor"],
    soldCount: "289 Sold",
  },
  {
    id: 85,
    name: "Turnip White Seeds",
    price: 950,
    priceText: "Rs. 950",
    originalPrice: "Rs. 1,380",
    rating: 4.1,
    image: "/images/products/turnip-white.jpg",
    category: "seeds",
    description: "White turnip variety for root vegetable production.",
    brand: "Turnip",
    inStock: true,
    features: ["White variety", "Root vegetable", "Good storage"],
    soldCount: "123 Sold",
  },
  {
    id: 86,
    name: "Pumpkin Giant Seeds",
    price: 1850,
    priceText: "Rs. 1,850",
    originalPrice: "Rs. 2,280",
    rating: 4.4,
    image: "/images/products/pumpkin-giant.jpg",
    category: "seeds",
    description: "Giant pumpkin variety for large fruit production.",
    brand: "Pumpkin",
    inStock: true,
    features: ["Giant variety", "Large fruits", "High yield"],
    soldCount: "45 Sold",
  },
  {
    id: 87,
    name: "Watermelon Sugar Seeds",
    price: 2150,
    priceText: "Rs. 2,150",
    originalPrice: "Rs. 2,580",
    rating: 4.5,
    image: "/images/products/watermelon-sugar.jpg",
    category: "seeds",
    description: "Sweet watermelon variety with high sugar content.",
    brand: "Watermelon",
    inStock: true,
    features: ["Sweet variety", "High sugar", "Juicy fruit"],
    soldCount: "67 Sold",
  },
  {
    id: 88,
    name: "Bitter Gourd Seeds",
    price: 1350,
    priceText: "Rs. 1,350",
    originalPrice: "Rs. 1,780",
    rating: 4.2,
    image: "/images/products/bitter-gourd.jpg",
    category: "seeds",
    description: "Bitter gourd variety with medicinal properties.",
    brand: "Bitter Gourd",
    inStock: true,
    features: ["Medicinal properties", "High nutrition", "Disease resistant"],
    soldCount: "89 Sold",
  },
  {
    id: 89,
    name: "Ridge Gourd Seeds",
    price: 1150,
    priceText: "Rs. 1,150",
    originalPrice: "Rs. 1,580",
    rating: 4.1,
    image: "/images/products/ridge-gourd.jpg",
    category: "seeds",
    description: "Ridge gourd variety for vegetable and fiber production.",
    brand: "Ridge Gourd",
    inStock: true,
    features: ["Dual purpose", "Vegetable production", "Fiber use"],
    soldCount: "156 Sold",
  },
  {
    id: 90,
    name: "Snake Gourd Seeds",
    price: 1250,
    priceText: "Rs. 1,250",
    originalPrice: "Rs. 1,680",
    rating: 4.0,
    image: "/images/products/snake-gourd.jpg",
    category: "seeds",
    description: "Long snake gourd variety for unique vegetable production.",
    brand: "Snake Gourd",
    inStock: true,
    features: ["Long variety", "Unique vegetable", "High yield"],
    soldCount: "78 Sold",
  },

  // Final products to complete 100+
  {
    id: 91,
    name: "Pesticide Adjuvant",
    price: 1450,
    priceText: "Rs. 1,450",
    originalPrice: "Rs. 1,880",
    rating: 4.3,
    image: "/images/products/adjuvant.jpg",
    category: "specialty",
    description: "Spray adjuvant for improved pesticide effectiveness.",
    brand: "Adjuvant",
    inStock: true,
    features: ["Spray adjuvant", "Improved effectiveness", "Better coverage"],
    soldCount: "234 Sold",
  },
  {
    id: 92,
    name: "Wetting Agent",
    price: 950,
    priceText: "Rs. 950",
    originalPrice: "Rs. 1,380",
    rating: 4.1,
    image: "/images/products/wetting-agent.jpg",
    category: "specialty",
    description: "Wetting agent for better spray coverage and penetration.",
    brand: "Wetting",
    inStock: true,
    features: ["Better coverage", "Spray penetration", "Surface tension"],
    soldCount: "167 Sold",
  },
  {
    id: 93,
    name: "Sticker Spreader",
    price: 1150,
    priceText: "Rs. 1,150",
    originalPrice: "Rs. 1,580",
    rating: 4.2,
    image: "/images/products/sticker-spreader.jpg",
    category: "specialty",
    description: "Sticker spreader for improved spray adhesion.",
    brand: "Sticker",
    inStock: true,
    features: ["Spray adhesion", "Rain fastness", "Extended contact"],
    soldCount: "123 Sold",
  },
  {
    id: 94,
    name: "pH Buffer Solution",
    price: 850,
    priceText: "Rs. 850",
    originalPrice: "Rs. 1,280",
    rating: 4.0,
    image: "/images/products/ph-buffer.jpg",
    category: "specialty",
    description: "pH buffer solution for spray tank water conditioning.",
    brand: "pH Buffer",
    inStock: true,
    features: ["pH adjustment", "Water conditioning", "Spray optimization"],
    soldCount: "289 Sold",
  },
  {
    id: 95,
    name: "Anti-Foaming Agent",
    price: 750,
    priceText: "Rs. 750",
    originalPrice: "Rs. 1,180",
    rating: 3.9,
    image: "/images/products/anti-foam.jpg",
    category: "specialty",
    description: "Anti-foaming agent for spray tank applications.",
    brand: "Anti-Foam",
    inStock: true,
    features: ["Foam control", "Spray tank", "Application efficiency"],
    soldCount: "345 Sold",
  },
  {
    id: 96,
    name: "Drift Control Agent",
    price: 1250,
    priceText: "Rs. 1,250",
    originalPrice: "Rs. 1,680",
    rating: 4.2,
    image: "/images/products/drift-control.jpg",
    category: "specialty",
    description: "Drift control agent for precise spray application.",
    brand: "Drift Control",
    inStock: true,
    features: ["Drift reduction", "Precise application", "Environmental safety"],
    soldCount: "89 Sold",
  },
  {
    id: 97,
    name: "Spray Marker Dye",
    price: 650,
    priceText: "Rs. 650",
    originalPrice: "Rs. 1,080",
    rating: 4.0,
    image: "/images/products/marker-dye.jpg",
    category: "specialty",
    description: "Spray marker dye for application tracking.",
    brand: "Marker Dye",
    inStock: true,
    features: ["Application tracking", "Visual marking", "Coverage indication"],
    soldCount: "456 Sold",
  },
  {
    id: 98,
    name: "Tank Cleaner",
    price: 950,
    priceText: "Rs. 950",
    originalPrice: "Rs. 1,380",
    rating: 4.1,
    image: "/images/products/tank-cleaner.jpg",
    category: "specialty",
    description: "Tank cleaner for spray equipment maintenance.",
    brand: "Tank Clean",
    inStock: true,
    features: ["Equipment cleaning", "Residue removal", "Tank maintenance"],
    soldCount: "234 Sold",
  },
  {
    id: 99,
    name: "Nozzle Cleaner Kit",
    price: 1150,
    priceText: "Rs. 1,150",
    originalPrice: "Rs. 1,580",
    rating: 4.2,
    image: "/images/products/nozzle-cleaner.jpg",
    category: "specialty",
    description: "Complete nozzle cleaning kit for spray equipment.",
    brand: "Nozzle Kit",
    inStock: true,
    features: ["Nozzle cleaning", "Complete kit", "Equipment maintenance"],
    soldCount: "167 Sold",
  },
  {
    id: 100,
    name: "Calibration Kit",
    price: 2450,
    priceText: "Rs. 2,450",
    originalPrice: "Rs. 2,880",
    rating: 4.4,
    image: "/images/products/calibration-kit.jpg",
    category: "specialty",
    description: "Spray calibration kit for accurate application rates.",
    brand: "Calibration",
    inStock: true,
    features: ["Spray calibration", "Accurate rates", "Professional tool"],
    soldCount: "78 Sold",
  },
]

export const categories = [
  {
    id: "pesticides",
    name: "Pesticides & Insecticides",
    icon: "🐛",
    count: products.filter((p) => p.category === "pesticides").length,
  },
  {
    id: "fertilizers",
    name: "Fertilizers & Nutrients",
    icon: "🌱",
    count: products.filter((p) => p.category === "fertilizers").length,
  },
  {
    id: "seeds",
    name: "Seeds & Varieties",
    icon: "🌾",
    count: products.filter((p) => p.category === "seeds").length,
  },
  {
    id: "specialty",
    name: "Specialty Products",
    icon: "⭐",
    count: products.filter((p) => p.category === "specialty").length,
  },
]

export function getProductById(id: number): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (!category) return products
  return products.filter((product) => product.category === category)
}

export function searchProducts(query: string, category?: string): Product[] {
  let filtered = products

  if (category) {
    filtered = filtered.filter((product) => product.category === category)
  }

  if (query) {
    const searchTerm = query.toLowerCase()
    filtered = filtered.filter(
      (product) =>
        product.name.toLowerCase().includes(searchTerm) ||
        product.brand.toLowerCase().includes(searchTerm) ||
        product.description.toLowerCase().includes(searchTerm),
    )
  }

  return filtered
}
